default_language_version:
  python: python3.12
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: docs/references
      - id: trailing-whitespace
  - repo: https://github.com/python-poetry/poetry
    rev: "1.8.0"
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-install
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.4.2
    hooks:
      - id: ruff
      - id: ruff-format
  - repo: local
    hooks:
      - id: add-references-docs
        name: add-references-docs
        entry: pdoc
        args:
          [
            "--docformat",
            "google",
            "--output-directory",
            "docs/references",
            "src/mjv_todo_api",
          ]
        language: python
        types: [python]
        files: src
        pass_filenames: false

ci:
  autofix_commit_msg: 🎨 [pre-commit.ci] Auto format from pre-commit.c
  autoupdate_commit_msg: ⬆ [pre-commit.ci] pre-commit au
